version: 0.0
os: linux
files:
  - source: /
    destination: /var/play/
hooks:
  BeforeInstall:
    - location: shell/appspec-BeforeInstall.sh
      timeout: 300
      runas: rl_app
  ApplicationStop:
    - location: shell/appspec-ApplicationStop.sh
      timeout: 300
      runas: rl_app
#  ApplicationStart:
#    - location: /etc/init.d/play start
#      timeout: 300
#      runas: root
