version: 0.0
os: linux
files:
  - source: /
    destination: /var/play/
hooks:
  BeforeInstall:
    - location: shell/appspec-BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: shell/appspec-AfterInstall.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: shell/appspec-ApplicationStop.sh
      timeout: 300
      runas: rl_app
  ApplicationStart:
    - location: shell/appspec-ApplicationStart.sh
      timeout: 300
      runas: rl_app
