version: 0.0
os: linux
files:
  - source: /
    destination: /var/play/
#hooks:
#  BeforeInstall:
#    - location: mv api before_api
#      timeout: 300
#      runas: root
#    - location: mv api-* api
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: /etc/init.d/play stop
#      timeout: 300
#      runas: root
#  ApplicationStart:
#    - location: /etc/init.d/play start
#      timeout: 300
#      runas: root
